[build]
buildCommand = "pnpm install && pnpm run build"
watchPatterns = ["docs-site/**"]

[deploy]
startCommand = "pnpm run serve --port $PORT --host 0.0.0.0"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
